/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RMI.views;

import RMI.recepcion.RecepcionClient;
import RMI.elements.Ciudad;
import RMI.elements.Departamento;
import RMI.elements.Paquete;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 *
 * @author nata_
 */
public class RegistroEnvio extends javax.swing.JDialog {

    private RecepcionClient recepcionClient;
    ImageIcon logo = new ImageIcon("src/RMI/images/camion1.png");

    ImageIcon fondo = new ImageIcon("src/RMI/images/fondo.jpg");

    public RegistroEnvio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        labelLogo.setIcon(logo);
        labelFondo.setIcon(fondo);
    }

    public void setRecepcionClient(RecepcionClient clienteRecepcion) {
        this.recepcionClient = clienteRecepcion;
        if(recepcionClient.obtenerDepartamentos() == null){
            System.out.println("hola");
        }
        for (Departamento departamento : this.recepcionClient.obtenerDepartamentos()) {
            CBDepEmisor.addItem(departamento.getNombre());
            CBDepReceptor.addItem(departamento.getNombre());
        }
        for (Ciudad ciudad : this.recepcionClient.obtenerCiudades((String) CBDepEmisor.getSelectedItem())) {
            CBCiuEmisor.addItem(ciudad.getNombre() + "- (" + ciudad.getCoordenadas().getLatitud() + ", " + ciudad.getCoordenadas().getLongitud() + ")");
        }
        for (Ciudad ciudad : this.recepcionClient.obtenerCiudades((String) CBDepReceptor.getSelectedItem())) {
            CBCiuReceptor.addItem(ciudad.getNombre() + "- (" + ciudad.getCoordenadas().getLatitud() + ", " + ciudad.getCoordenadas().getLongitud() + ")");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBDepEmisor = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmisor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CBCiuEmisor = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        txtReceptor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CBDepReceptor = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        CBCiuReceptor = new javax.swing.JComboBox<String>();
        txtPesoPaq = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBDepEmisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDepEmisorActionPerformed(evt);
            }
        });
        getContentPane().add(CBDepEmisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 250, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Departamento emisor:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 185, 23));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre emisor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(txtEmisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 248, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ciudad emisor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 185, 23));

        CBCiuEmisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCiuEmisorActionPerformed(evt);
            }
        });
        getContentPane().add(CBCiuEmisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 310, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre receptor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, 20));
        getContentPane().add(txtReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 248, 40));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Departamento receptor:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 190, 20));

        CBDepReceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDepReceptorActionPerformed(evt);
            }
        });
        getContentPane().add(CBDepReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 248, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ciudad receptor:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 140, 20));

        CBCiuReceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCiuReceptorActionPerformed(evt);
            }
        });
        getContentPane().add(CBCiuReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 330, 40));
        getContentPane().add(txtPesoPaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 206, 34));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peso paquete:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        btnRegistrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnRegistrar.setText("Registrar Paquete");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 200, 40));

        btnCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 200, 40));
        getContentPane().add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 190, 70));
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBDepEmisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDepEmisorActionPerformed
        CBCiuEmisor.removeAllItems();
        for (Ciudad ciudad : this.recepcionClient.obtenerCiudades((String) CBDepEmisor.getSelectedItem())) {
            CBCiuEmisor.addItem(ciudad.getNombre() + "- (" + ciudad.getCoordenadas().getLatitud() + ", " + ciudad.getCoordenadas().getLongitud() + ")");
        }
    }//GEN-LAST:event_CBDepEmisorActionPerformed

    private void CBDepReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDepReceptorActionPerformed
        CBCiuReceptor.removeAllItems();
        for (Ciudad ciudad : this.recepcionClient.obtenerCiudades((String) CBDepReceptor.getSelectedItem())) {
            CBCiuReceptor.addItem(ciudad.getNombre() + "- (" + ciudad.getCoordenadas().getLatitud() + ", " + ciudad.getCoordenadas().getLongitud() + ")");
        }
    }//GEN-LAST:event_CBDepReceptorActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombreEmisor = txtEmisor.getText();
        String departamentoEmisor = CBDepEmisor.getSelectedItem().toString();
        String ciudadEmisor = CBCiuEmisor.getSelectedItem().toString();

        ciudadEmisor = ciudadEmisor.split("-")[0].replace("(", "");        
        String nombreReceptor = txtReceptor.getText();
        String departamentoReceptor = CBDepReceptor.getSelectedItem().toString();
        String ciudadReceptor = CBCiuReceptor.getSelectedItem().toString();
        ciudadReceptor = ciudadReceptor.split("-")[0].replace("(", "");
        
        System.out.println(ciudadEmisor);
        System.out.println(ciudadReceptor);
        float pesoPaquete = 0;                
        if (nombreEmisor.equals("") || departamentoEmisor.equals("") || ciudadEmisor.equals("")
                || nombreReceptor.equals("") || departamentoReceptor.equals("") || ciudadReceptor.equals("")) {
            JOptionPane.showMessageDialog(null, "No deben haber campos vácios");
            return;
        }

        try {
            pesoPaquete = Float.parseFloat(txtPesoPaq.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "El valor ingresado para peso no es válido, debe ser numérico");
            return;
        }

        Paquete paquete = new Paquete(nombreEmisor, departamentoEmisor, ciudadEmisor, nombreReceptor, departamentoReceptor, ciudadReceptor, pesoPaquete);
        this.recepcionClient.registrarPaquete(paquete);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void CBCiuReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCiuReceptorActionPerformed

    }//GEN-LAST:event_CBCiuReceptorActionPerformed

    private void CBCiuEmisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCiuEmisorActionPerformed

    }//GEN-LAST:event_CBCiuEmisorActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCiuEmisor;
    private javax.swing.JComboBox<String> CBCiuReceptor;
    private javax.swing.JComboBox<String> CBDepEmisor;
    private javax.swing.JComboBox<String> CBDepReceptor;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JTextField txtEmisor;
    private javax.swing.JTextField txtPesoPaq;
    private javax.swing.JTextField txtReceptor;
    // End of variables declaration//GEN-END:variables
}
